name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      env:
        USER: ${{ secrets.USER }}
        PASS: ${{ secrets.PASS }}   
      run: |        
        docker build . --file Dockerfile --tag rahul2001docker/devops-ci-flask-webserver-2026:v1
        docker login -u $USER -p $PASS        
        docker push rahul2001docker/devops-ci-flask-webserver-2026:v1
